### ISSUE TITLE
Optimize DIstance Computation

### ISSUE THREAD

**Issue by AlVella** [GispoCoding/eis_toolkit#228]
The current implementation of distance_computation is actually quite slow to process dataset with high resolution.

I would like to suggest an alternative implementation of this functionality to speed up the process. I came up with the following function to compute distances with similar input data and output results as the current function.

This implementation:

1. Compute a meshgrid matrix of the coordinates of the input matrix using raster_profile. The meshgrid represent the coordinates of each pixel center.
2. For each pixel center, the distance to the nearest geometry is computed using the shapely.ops.nearest_points() function, selecting the nearest feature and then computing the distance between the pixel's center and this feature.
3. A numpy matrix similar to the meshgrid is returned with the distance to the nearest feature for each pixel.

```
from typing import Union
from rasterio import profiles, transform
from shapely.geometry import Point
from shapely.ops import nearest_points
from beartype import beartype
import geopandas as gpd
import numpy as np

def distance_computation(raster_profile: Union[profiles.Profile, dict], geometries: gpd.GeoDataFrame) -> np.ndarray:
    """Calculate distance from raster cell to nearest geometry.

    Args:
        raster_profile: The raster profile of the raster in which the distances
            to the nearest geometry are determined.
        geometries: The geometries to determine distance to.

    Returns:
        A 2D numpy array with the distances computed.

    """
    if raster_profile.get("crs") != geometries.crs:
        raise exceptions.NonMatchingCrsException("Expected coordinate systems to match between raster and geometries. ")
    if geometries.shape[0] == 0:
        raise exceptions.EmptyDataFrameException("Expected GeoDataFrame to not be empty.")

    raster_width = raster_profile.get("width")
    raster_height = raster_profile.get("height")

    if not isinstance(raster_width, int) or not isinstance(raster_height, int):
        raise exceptions.InvalidParameterValueException(
            f"Expected raster_profile to contain integer width and height. {raster_profile}"
        )
    
    raster_transform = raster_profile.get("transform")
    
    if not isinstance(raster_transform, transform.Affine):
        raise exceptions.InvalidParameterValueException(
            f"Expected raster_profile to contain an affine transformation. {raster_profile}"
        )

    cols, rows = np.meshgrid(
        np.arange(raster_width),
        np.arange(raster_height)) 
    point_xs, point_ys = transform.xy(transform=raster_transform, cols=cols, rows=rows)
    geometries_feat = geometries.geometry.unary_union

    distance_matrix = np.array(point_xs, copy=True)  
    for col in cols[0]:
        for row in range(0,len(cols),1):
            x = point_xs[row][col]
            y = point_ys[row][col]
            points_coo = Point(x,y)
            nearest = nearest_points(points_coo, geometries_feat)
            shortest_distance = nearest[0].distance(nearest[1])
            distance_matrix[row][col] = shortest_distance
    return distance_matrix
```

I did some testing with the Armorican Massif dataset, computing distances to faults with a raster grid of 1 000m (116 064 pixels). With the current implementation, computation took approximatively 15min. With this alternative function, it took 20 sec. Resulting distances matrix are similar.

I hope i'm not missing some obvious flaw, but I think it could be worth replacing the actual function to improve processing speed.

**Comment by nmaarnio** [comment]
Thanks, this looks promising to me! Could you comment / take a look @nialov ?

**Comment by nialov** [comment]
Yes, my original implementation was very naive. `unary_union` is probably the cause of the majority of the optimization performance as the problem is that the distance is first calculated to every geometry in `geometries` even though we only want the shortest distance. Therefore, I believe the below changes are enough to optimize the performance. Could you @AlVella test this implementation for if the performance with your large dataset improves similarly to what you mentioned?

~~~patch
diff --git a/eis_toolkit/vector_processing/distance_computation.py b/eis_toolkit/vector_processing/distance_computation.py
index 3f8f747..a4d0713 100644
--- a/eis_toolkit/vector_processing/distance_computation.py
+++ b/eis_toolkit/vector_processing/distance_computation.py
@@ -11,13 +11,9 @@ from eis_toolkit import exceptions
 
 def _shortest_distance_to_point(point: Point, geometries: gpd.GeoDataFrame) -> float:
     """Calculate shortest distance from geometries to point."""
-    # This could be sped up by using a spatial index to first choose only
-    # geometries that are close to the point
-    distances_to_point = geometries.distance(point)
-    shortest_distance: float = distances_to_point.min()
+    shortest_distance:float = geometries.distance(point)
     return shortest_distance
 
-
 @beartype
 def distance_computation(raster_profile: Union[profiles.Profile, dict], geometries: gpd.GeoDataFrame) -> np.ndarray:
     """Calculate distance from raster cell to nearest geometry.
@@ -75,6 +71,8 @@ def _distance_computation(
     cols = np.arange(raster_width)
     rows = np.arange(raster_height)
 
+    geometries = geometries.geometry.unary_union
+
     distance_matrix = np.array(
         [
             _calculate_row_distances(row=row, cols=cols, raster_transform=raster_transform, geometries=geometries)

~~~

**Comment by AlVella** [comment]
Yes, this implementation is working correctly. I ran it multiple time with the same dataset and it seems faster than my proposed implementation, with a processing time around 16 sec.

Tried it with a larger dataset (250m resolution, 1 847 098 pixels). Computation took 4 minutes with this implementation, 5 with the previously proposed one, so I would say it is quite effective.

**Comment by nialov** [comment]
I can create the pull request to implement the optimization. I do know that `unary_union` has not always been completely stable so I will probably try to implement some fallback mechanism and anyway update type annotations etc.
