### ISSUE TITLE
Optimize Distance to anomaly

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_toolkit#409]

**Comment by nmaarnio** [comment]
@nialov , would you have time to take this task? Based on recent feedback, `distance to anomaly` is requested to run much faster (also `distance computation`, #384 )

**Comment by nialov** [comment]
I believe the problem is `geopandas.GeoDataFrame.unary_union` here: <https://github.com/GispoCoding/eis_toolkit/blob/5c8d32e2164853d8d48581f50529a78202123ad9/eis_toolkit/vector_processing/distance_computation.py#L81>

Updates to `geopandas` and `shapely` might speed it up without code changes. I will try to check before the end of June.

If that does not solve the performance then you need to look at alternatives such as converting the geometries to raster cell values and calculating raster distances. The annoying thing is, that `GDAL` already implement the raster distance computations with high performance so you would just be replicating a `GDAL` function which you probably can not beat in terms of performance.

See: <https://github.com/GispoCoding/eis_toolkit/pull/324#issuecomment-1943435164>
